# Generated by Django 2.2.3 on 2019-07-31 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190731_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
