# Generated by Django 2.2.3 on 2019-08-01 14:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20190801_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(1), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0, 300))]),
        ),
    ]
